import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "./styles/page.module.css"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >    <aside className={styles.sidebar}>
          <h1>Botantical Muse</h1>
          <p>This is the site of an amazing artist</p>
        </aside>
        <main className={styles.main}>
            {children}
        </main>
      </body>
    </html>
  );
}
